---
- hosts: localhost
  connection: local
  vars_files:
     - ./vars/main.yml
  tasks:
  - name: Launch the new EC2 instances
    ec2:
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      key_name: "{{ keypair }}"
      instance_type:  t2.large
      instance_tags:
        Name: elk-cluster
      image: ami-01620a8c455b05ef8
      wait: yes
      group: launch-wizard-65
      count: 2
      vpc_subnet_id: subnet-6a5f7b42
      assign_public_ip: yes
      region: us-east-1
    register: ec2


  - name: Get public ip of newly created instance
    set_fact:
      instance_elk_master: "{{ ec2.instances[0].private_ip }}"
      instance_elk_second: "{{ ec2.instances[1].private_ip }}"
    register: result
    with_items: "{{ ec2.instances }}"


  - name: Add the newly created EC2 instance(s) to ansible host group
    lineinfile: dest={{ hostpath }}
      regexp={{ item.private_ip }}
      line="[node_{{ item.ami_launch_index }}]\n{{ item.private_ip }} {{hoststring}}"
      state=present
    with_items: "{{ ec2.instances}}"

  - name: Write host ip in elasticsearch master vars file
    replace:
      path: "../configure/vars/main.yml"
      regexp: 'master_node_host_ip:'
      replace: "master_node_host_ip: {{ instance_elk_master }}"

  - name: Write second node ip in elasticsearch master vars file
    replace:
      path: "../configure/vars/main.yml"
      regexp: 'second_node_ip:'
      replace: "second_node_ip: {{ instance_elk_second }}"

  - name: Wait 300 seconds, but only start checking after 60 seconds
    wait_for_connection:
      delay: 60
      timeout: 300

  
  #########################################################################
  - name: Launch the new EC2 instances
    ec2:
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      key_name: "{{ keypair }}"
      instance_type:  m3.medium
      instance_tags:
        Name: elk-nodes
      image: ami-01620a8c455b05ef8
      wait: yes
      group: launch-wizard-65
      count: 2
      vpc_subnet_id: subnet-6a5f7b42
      assign_public_ip: yes
      region: us-east-1
    register: ec2

  - name: Get public ip of newly created instance
    set_fact:
      instance_kibana: "{{ ec2.instances[0].private_ip }}"
      instance_log: "{{ ec2.instances[1].private_ip }}"
    register: result
    with_items: "{{ ec2.instances }}"

  - name: Add the newly created EC2 instance(s) to ansible host group
    lineinfile: dest={{ hostpath }}
      regexp={{ item.private_ip }}
      line="[nodes_{{ item.ami_launch_index }}]\n{{ item.private_ip }} {{hoststring}}"
      state=present
    with_items: "{{ ec2.instances}}"

  - name: Wait 300 seconds, but only start checking after 60 seconds
    wait_for_connection:
      delay: 60
      timeout: 300
