---
- hosts: localhost
  vars_files:
      - ../vars/vars.yml
  tasks:
    # Configurations for Percona Cluster
    # Change the ip's in  master node
    - name: Change the config file for Bootstrap node
      replace:
        path: ./files/percona1/wsrep.cnf
        regexp: "wsrep_cluster_address=gcomm://"
        replace: "wsrep_cluster_address=gcomm://{{ percona_0 }},{{ percona_1 }},{{ percona_2 }}"

    # Add master server host IP
    - name: Add the bootstrap node ip into cofig file
      replace:
        path: ./files/percona1/wsrep.cnf
        regexp: "wsrep_node_address="
        replace: "wsrep_node_address={{ percona_0 }}"

    # Change the ip's in first data node
    - name: Change the config file for first data node
      replace:
        path: ./files/percona2/wsrep.cnf
        regexp: "wsrep_cluster_address=gcomm://"
        replace: "wsrep_cluster_address=gcomm://{{ percona_0 }},{{ percona_1 }},{{ percona_2 }}"

    #Add data node host IP
    - name: Add the first data node ip into cofig file
      replace:
        path: ./files/percona2/wsrep.cnf
        regexp: "wsrep_node_address="
        replace: "wsrep_node_address={{ percona_1 }}"

    # Change the ip's in second data node
    - name: Change the config file for second data node
      replace:
        path: ./files/percona3/wsrep.cnf
        regexp: "wsrep_cluster_address=gcomm://"
        replace: "wsrep_cluster_address=gcomm://{{ percona_0 }},{{ percona_1 }},{{ percona_2 }}"

    # Add data second node host IP
    - name: Add the second node ip into cofig file
      replace:
        path: ./files/percona3/wsrep.cnf
        regexp: "wsrep_node_address="
        replace: "wsrep_node_address={{ percona_2 }}"

    # configurations for HAProxy server
    - name: Add percona cluser ip's in haproxy config file
      replace:
        path: ./files/haproxy.cfg
        regexp: "^(.*)server percona1(.*)$"
        replace: "server percona1 {{ percona_0 }}:3306 check port 9200 inter 12000 rise 3 fall 3"

    - name: Add percona cluser ip's in haproxy config file
      replace:
        path: ./files/haproxy.cfg
        regexp: "^(.*)server percona2(.*)$"
        replace: "server percona2 {{ percona_1 }}:3306 check port 9200 inter 12000 rise 3 fall 3"

    - name: Add percona cluser ip's in haproxy config file
      replace:
        path: ./files/haproxy.cfg
        regexp: "^(.*)server percona3(.*)$"
        replace: "server percona3 {{ percona_2 }}:3306 check port 9200 inter 12000 rise 3 fall 3"

    - name: Add line to HAProxy config file
      lineinfile:
          dest: ./files/haproxy.cfg
          line: "server percona1 {{ percona_0 }}:3306 check port 9200 inter 12000 rise 3 fall 3"

    - name: Add line to HAProxy config file
      lineinfile:
          dest: ./files/haproxy.cfg
          line: "server percona2 {{ percona_1 }}:3306 check port 9200 inter 12000 rise 3 fall 3 backup"

    - name: Add line to HAProxy config file
      lineinfile:
          dest: ./files/haproxy.cfg
          line: "server percona3 {{ percona_2 }}:3306 check port 9200 inter 12000 rise 3 fall 3 backup"