---
- hosts: nodes_1
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: add repo for java 8
      become: yes
      apt_repository: repo='ppa:webupd8team/java' state=present

    - name: set licence selected
      become: yes
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

    - name: set licence seen
      become: yes
      shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections

    - name: install java 8
      become: yes
      apt: name=oracle-java8-installer state=latest force=yes

    # Add Logstash apt key
    - name: Add Logstash apt key.
      become: true
      shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

    # Add logstash packages
    - name: Adding Logstash https
      become: true
      shell: sudo apt-get install apt-transport-https

    # Add the Logstash repo
    - name: Save the logstash repo
      become: true
      shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

    # Install logstash
    - name: Installing Logstash
      become: true
      shell: sudo apt-get update && sudo apt-get install logstash

    # Start Logstash
    - name: Starting Logstash
      become: true
      service:
        name: logstash
        state: started

    # Configure the configuration of logstash
    - name: Configure the logstash
      become: true
      copy:
        src: ./logstash.conf
        dest: /etc/logstash/conf.d/

    # Change the configration of logstash output
    - name: Change the elasticsearch ip for output in logstash config
      become: true
      lineinfile:
        dest: /etc/logstash/conf.d/logstash.conf
        regexp: '^(.*)hosts(.*)$'
        line: '     hosts ​ =>​ ​ "{{ master_node_host_ip }}:9200"'
        backrefs: yes

    - name: restart logstash
      become: true
      service: name=logstash state=restarted


